//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class ADVERTISEMENT
    {
        public int ADVERTISEMENTID { get; set; }
        public Nullable<int> GALERYID { get; set; }
        public string SOURCE { get; set; }
    
        public virtual GALERY GALERY { get; set; }
    }
    
}
