//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class ADVERTISEMENTTYPE
    {
        public int ADVERTISEMENTTYPEID { get; set; }
        public string ADVERTISEMENTTYPENAME { get; set; }
    
        public virtual ADVERTISEMENT ADVERTISEMENT { get; set; }
    }
    
}
