//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class CategoryType
    {
        public CategoryType()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int CATEGORYTYPEID { get; set; }
        public string CATEGORYTYPENAME { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
    }
    
}
