//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class CATEGORYTYPE
    {
        public CATEGORYTYPE()
        {
            this.CATEGORY = new HashSet<CATEGORY>();
        }
    
        public int CATEGORYTYPEID { get; set; }
        public string CATEGORYTYPENAME { get; set; }
    
        public virtual ICollection<CATEGORY> CATEGORY { get; set; }
    }
    
}
