//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class Galery
    {
        public Galery()
        {
            this.Picture = new HashSet<Picture>();
            this.GALERYHASHTAGS = new HashSet<GaleryHashTag>();
        }
    
        public int GaleryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string GaleryName { get; set; }
        public Nullable<int> PeopleLikeCount { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<GaleryHashTag> GALERYHASHTAGS { get; set; }
    }
    
}
