//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Nayys
{
    public partial class NAYSSEntities : DbContext
    {
        public NAYSSEntities()
            : base("name=NAYSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> CATEGORY { get; set; }
        public DbSet<Galery> GALERY { get; set; }
        public DbSet<Picture> PICTURE { get; set; }
        public DbSet<Roles> ROLES { get; set; }
        public DbSet<Users> USERS { get; set; }
        public DbSet<CategoryType> CategoryTypes1 { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<GaleryHashTag> GALERYHASHTAGS { get; set; }
        public DbSet<PictureHashTag> PICTUREHASHTAGS { get; set; }
    }
}
