//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Nayys
{
    public partial class NayysEntities : DbContext
    {
        public NayysEntities()
            : base("name=NayysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADVERTISEMENT> ADVERTISEMENT { get; set; }
        public DbSet<CATEGORY> CATEGORY { get; set; }
        public DbSet<CATEGORYTYPE> CATEGORYTYPE { get; set; }
        public DbSet<GALERY> GALERY { get; set; }
        public DbSet<GALERYHASHTAGS> GALERYHASHTAGS { get; set; }
        public DbSet<PICTURE> PICTURE { get; set; }
        public DbSet<PICTUREHASHTAGS> PICTUREHASHTAGS { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<ADVERTISEMENTTYPE> ADVERTISEMENTTYPE { get; set; }
    }
}
