//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class Picture
    {
        public Picture()
        {
            this.PICTUREHASHTAGS = new HashSet<PictureHashTag>();
        }
    
        public System.Guid PictureID { get; set; }
        public Nullable<int> GaleryID { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public string SourceLink { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Galery Galery { get; set; }
        public virtual ICollection<PictureHashTag> PICTUREHASHTAGS { get; set; }
    }
    
}
