//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class PictureHashTag
    {
        public System.Guid PICTUREID { get; set; }
        public string HASHTAG { get; set; }
    
        public virtual Picture Picture { get; set; }
    }
    
}
