//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Nayys
{
    public partial class PICTURE
    {
        public PICTURE()
        {
            this.PICTUREHASHTAGS = new HashSet<PICTUREHASHTAGS>();
        }
    
        public System.Guid PICTUREID { get; set; }
        public Nullable<int> GALERYID { get; set; }
        public string PATH { get; set; }
        public string DESCRIPTION { get; set; }
        public string SOURCELINK { get; set; }
        public string SUBJECT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual GALERY GALERY { get; set; }
        public virtual ICollection<PICTUREHASHTAGS> PICTUREHASHTAGS { get; set; }
    }
    
}
